/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class NativeSheet {
  get info(): RangeInfo
  batch(start: number, count: number): Promise<Batch>
  close(): Promise<void>
}

export declare class NativeWorkbook {
  get info(): WorkbookInfo
  loadSheet(index: number, maxCells: number, formulas: boolean): Promise<NativeSheet>
  vbaProject(maxBytes: number): Promise<VbaProject | null>
  close(): Promise<void>
}

export interface Batch {
  rows: Array<Array<CellValue>>
}

export type CellValue = string | number | boolean | null | SpecialValue

export interface DefinedName {
  name: string
  formula: string
}

export declare function openBytes(bytes: Buffer, maxBytes: number): Promise<NativeWorkbook>

export declare function openPath(path: string, maxBytes: number): Promise<NativeWorkbook>

export interface RangeInfo {
  row?: number
  column?: number
  rowCount: number
  columnCount: number
}

export interface SheetInfo {
  name: string
  index: number
  kind: string
  visibility: string
}

export interface SpecialValue {
  kind: string
  value: number | string
  /** Wall-clock components: year, month, day, hour, minute, second, millisecond. */
  calendar?: Array<number>
}

export interface VbaModule {
  name: string
  source: string
}

export interface VbaProject {
  modules: Array<VbaModule>
  references: Array<VbaReference>
}

export interface VbaReference {
  name: string
  description: string
  path: string
}

export interface WorkbookInfo {
  format: string
  sheets: Array<SheetInfo>
  definedNames: Array<DefinedName>
}
